### ISSUE TITLE
Number of GPUs

### ISSUE THREAD

**Issue by ShoufaChen** [lulutang0608/Point-BERT#14]
Hi,

Thanks for your great work.

Would you mind sharing how many GPUs did you use for training dVAE, pre-training, and fine-tuning?

**Comment by yuxumin** [comment]
Hi, thanks for your interest in our work.

See [here](https://github.com/lulutang0608/Point-BERT/issues/9#issuecomment-998722151)

**Comment by ShoufaChen** [comment]
Hi,
Thanks for your quick reply.

> The training of dVAE takes another 20 hours on one Nvidia 2080Ti at the beginning.

I tried to use 2 GPUs for training dVAE but failed with following info:
```
...
2022-01-02 15:38:24,041 - ShapeNet-55 - INFO - [DATASET] 10518 instances were loaded                                                                                                                          
2022-01-02 15:38:30,973 - dvae - INFO - Using Data parallel ...                                                                                                                                               
Traceback (most recent call last):                                                                                                                                                                            
  File "main.py", line 72, in <module>                                                                                                                                                                        
    main()                                                                                                                                                                                                    
  File "main.py", line 68, in main                                                                                                                                                                            
    run_net(args, config, train_writer, val_writer)                                                                                                                                                           
  File "/home/chenshoufa/workspace/Point-BERT/tools/runner.py", line 136, in run_net                                                                                                                          
    _loss.backward()                                                                                                                                                                                          
  File "/home/chenshoufa/anaconda3/envs/pointbert/lib/python3.8/site-packages/torch/tensor.py", line 245, in backward                                                                                         
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)                                                                                                                        
  File "/home/chenshoufa/anaconda3/envs/pointbert/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward                                                                              
    Variable._execution_engine.run_backward(                                                                                                                                                                  
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR                                                                                                                                                        
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.                                 
                                                                                                                                                                                                              
import torch                                                                                                                                                                                                  
torch.backends.cuda.matmul.allow_tf32 = True                                                                                                                                                                  
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([2048, 512, 1, 32], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(512, 256, kernel_size=[1, 1], padding=[0, 0], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams 
    data_type = CUDNN_DATA_FLOAT
    padding = [0, 0, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x7fdb28016aa0
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 2048, 512, 1, 32, 
    strideA = 16384, 32, 32, 1, 
output: TensorDescriptor 0x7fdb280168d0
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 2048, 256, 1, 32, 
    strideA = 8192, 32, 32, 1, 
weight: FilterDescriptor 0x7fdb28018140
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 256, 512, 1, 1, 
Pointer addresses: 
    input: 0x7fe6a5540000
    output: 0x7fe644000000
    weight: 0x7fe776124000
```

Do you meet a similar problem?  Single GPU is OK.

**Comment by yuxumin** [comment]
No similar problems met in my experiments. 

The code for training dVAE is built upon [PoinTr](https://github.com/yuxumin/PoinTr), the code is supported for multi-gpu training (include dp and ddp).
I run the command in my env:
`bash scripts/train.sh 0,1 --config cfgs/ShapeNet55_models/dvae.yaml`
and the log is:
![QQ截图20220102160608](https://user-images.githubusercontent.com/29698233/147869842-fc4026d2-55d3-4ebc-ad06-a6aa36a8a6f7.png)

**Comment by ShoufaChen** [comment]
Would you mind sharing your pytorch and cuda, cudnn version?

**Comment by yuxumin** [comment]
Sure,
```
pytorch                   1.7.0           py3.7_cuda11.0.221_cudnn8.0.3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
```
Pytorch1.7 + cuda 11.0

**Comment by ShoufaChen** [comment]
Hi, after changing pytorch to pytorch1.7, I got the same error when using 2 GPUs.
Single GPU also fails with OOM error. I use 3090 (24GB)

```
2022-01-02 17:05:17,094 - dvae - INFO - Using Data parallel ...
Traceback (most recent call last):
  File "main.py", line 72, in <module>
    main()
  File "main.py", line 68, in main
    run_net(args, config, train_writer, val_writer)
  File "/home/chenshoufa/workspace/Point-BERT/tools/runner.py", line 130, in run_net
    ret = base_model(points, temperature = temp, hard = False)
  File "/home/chenshoufa/anaconda3/envs/pointbert/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/chenshoufa/anaconda3/envs/pointbert/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/chenshoufa/anaconda3/envs/pointbert/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/chenshoufa/workspace/Point-BERT/models/dvae.py", line 298, in forward
    logits = self.encoder(neighborhood)   #  B G C
  File "/home/chenshoufa/anaconda3/envs/pointbert/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/chenshoufa/workspace/Point-BERT/models/dvae.py", line 172, in forward
    feature = self.second_conv(feature) # BG 1024 n
  File "/home/chenshoufa/anaconda3/envs/pointbert/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/chenshoufa/anaconda3/envs/pointbert/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/chenshoufa/anaconda3/envs/pointbert/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/chenshoufa/anaconda3/envs/pointbert/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 258, in forward
    return F.conv1d(input, self.weight, self.bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 18.06 GiB (GPU 0; 23.70 GiB total capacity; 1.12 GiB already allocated; 18.06 GiB free; 4.43 GiB reserved in total by PyTorch)

```

**Comment by yuxumin** [comment]
Hi, 

> Hi, after changing pytorch to pytorch1.7, I got the same error when using 2 GPUs.

I haven't met the similar problem while training the network with multi-gpus. Have you tried the `dist_train.sh`? 
According to your log, there may be something wrong with your cudnn? 

> Single GPU also fails with OOM error. I use 3090 (24GB)

Reduce the batchsize? But it is strange. I can train the dVAE with 64 bs with only one Nvidia 2080Ti.

**Comment by ShoufaChen** [comment]
I solved this problem finally by install latest pytorch:
`linux-64/pytorch-1.10.1-py3.8_cuda11.1_cudnn8.0.5_0`.

Thanks again for your kind help.
