### ISSUE TITLE
Pre-training dVAE on ModelNet40

### ISSUE THREAD

**Issue by sw778** [lulutang0608/Point-BERT#38]
Hello,
I try to use ModelNet40 for pre-training of dVAE. I changed the dataset_name in runner.py to ModelNet40 and modified the code as shown in the picture. In addition, I also configured the dvae.yaml file about ModelNet40. But when I start training I get "KeyError: 'ModelNet'". I don't know why this problem occurs, is it related to the json file? , or do you have any good suggestions? Thanks.

![2022-05-07 18-57-38 的屏幕截图](https://user-images.githubusercontent.com/81848293/167252209-89e0ab0c-132d-4386-b6c3-b18a6f48f630.png)

`(pointbert) ws666@ws666-OMEN-by-HP-Laptop-15-dc1xxx:~/Point-BERT-master$ bash scripts/train.sh 0 --config cfgs/ModelNet_models/dvae.yaml --exp_name modelnetDvae
+ GPUS=0
+ PY_ARGS='--config cfgs/ModelNet_models/dvae.yaml --exp_name modelnetDvae'
+ CUDA_VISIBLE_DEVICES=0
+ python main.py --config cfgs/ModelNet_models/dvae.yaml --exp_name modelnetDvae
2022-05-07 18:53:55,248 - dvae - INFO - Copy the Config file from cfgs/ModelNet_models/dvae.yaml to ./experiments/dvae/ModelNet_models/modelnetDvae/config.yaml
2022-05-07 18:53:55,248 - dvae - INFO - args.config : cfgs/ModelNet_models/dvae.yaml
2022-05-07 18:53:55,248 - dvae - INFO - args.launcher : none
2022-05-07 18:53:55,248 - dvae - INFO - args.local_rank : 0
2022-05-07 18:53:55,249 - dvae - INFO - args.num_workers : 4
2022-05-07 18:53:55,249 - dvae - INFO - args.seed : 0
2022-05-07 18:53:55,249 - dvae - INFO - args.deterministic : False
2022-05-07 18:53:55,249 - dvae - INFO - args.sync_bn : False
2022-05-07 18:53:55,249 - dvae - INFO - args.exp_name : modelnetDvae
2022-05-07 18:53:55,249 - dvae - INFO - args.start_ckpts : None
2022-05-07 18:53:55,249 - dvae - INFO - args.ckpts : None
2022-05-07 18:53:55,249 - dvae - INFO - args.val_freq : 1
2022-05-07 18:53:55,249 - dvae - INFO - args.resume : False
2022-05-07 18:53:55,249 - dvae - INFO - args.test : False
2022-05-07 18:53:55,249 - dvae - INFO - args.finetune_model : False
2022-05-07 18:53:55,249 - dvae - INFO - args.scratch_model : False
2022-05-07 18:53:55,249 - dvae - INFO - args.label_smoothing : False
2022-05-07 18:53:55,249 - dvae - INFO - args.mode : None
2022-05-07 18:53:55,249 - dvae - INFO - args.way : -1
2022-05-07 18:53:55,249 - dvae - INFO - args.shot : -1
2022-05-07 18:53:55,249 - dvae - INFO - args.fold : -1
2022-05-07 18:53:55,249 - dvae - INFO - args.experiment_path : ./experiments/dvae/ModelNet_models/modelnetDvae
2022-05-07 18:53:55,249 - dvae - INFO - args.tfboard_path : ./experiments/dvae/ModelNet_models/TFBoard/modelnetDvae
2022-05-07 18:53:55,249 - dvae - INFO - args.log_name : dvae
2022-05-07 18:53:55,249 - dvae - INFO - args.use_gpu : True
2022-05-07 18:53:55,249 - dvae - INFO - args.distributed : False
2022-05-07 18:53:55,249 - dvae - INFO - config.optimizer = edict()
2022-05-07 18:53:55,249 - dvae - INFO - config.optimizer.type : AdamW
2022-05-07 18:53:55,249 - dvae - INFO - config.optimizer.kwargs = edict()
2022-05-07 18:53:55,250 - dvae - INFO - config.optimizer.kwargs.lr : 0.0005
2022-05-07 18:53:55,250 - dvae - INFO - config.optimizer.kwargs.weight_decay : 0.0005
2022-05-07 18:53:55,250 - dvae - INFO - config.scheduler = edict()
2022-05-07 18:53:55,250 - dvae - INFO - config.scheduler.type : CosLR
2022-05-07 18:53:55,250 - dvae - INFO - config.scheduler.kwargs = edict()
2022-05-07 18:53:55,250 - dvae - INFO - config.scheduler.kwargs.epochs : 300
2022-05-07 18:53:55,250 - dvae - INFO - config.scheduler.kwargs.initial_epochs : 10
2022-05-07 18:53:55,250 - dvae - INFO - config.scheduler.kwargs.warming_up_init_lr : 5e-05
2022-05-07 18:53:55,250 - dvae - INFO - config.temp = edict()
2022-05-07 18:53:55,250 - dvae - INFO - config.temp.start : 1
2022-05-07 18:53:55,250 - dvae - INFO - config.temp.target : 0.0625
2022-05-07 18:53:55,250 - dvae - INFO - config.temp.ntime : 100000
2022-05-07 18:53:55,250 - dvae - INFO - config.kldweight = edict()
2022-05-07 18:53:55,250 - dvae - INFO - config.kldweight.start : 0
2022-05-07 18:53:55,250 - dvae - INFO - config.kldweight.target : 0.1
2022-05-07 18:53:55,250 - dvae - INFO - config.kldweight.ntime : 100000
2022-05-07 18:53:55,250 - dvae - INFO - config.dataset = edict()
2022-05-07 18:53:55,250 - dvae - INFO - config.dataset.train = edict()
2022-05-07 18:53:55,250 - dvae - INFO - config.dataset.train._base_ = edict()
2022-05-07 18:53:55,250 - dvae - INFO - config.dataset.train._base_.NAME : ModelNet
2022-05-07 18:53:55,250 - dvae - INFO - config.dataset.train._base_.DATA_PATH : data/ModelNet/modelnet40_normal_resampled/modelnet40_normal_resampled
2022-05-07 18:53:55,250 - dvae - INFO - config.dataset.train._base_.N_POINTS : 1024
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.train._base_.NUM_CATEGORY : 2
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.train._base_.USE_NORMALS : False
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.train.others = edict()
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.train.others.subset : train
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.train.others.npoints : 1024
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.train.others.bs : 2
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.val = edict()
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.val._base_ = edict()
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.val._base_.NAME : ModelNet
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.val._base_.DATA_PATH : data/ModelNet/modelnet40_normal_resampled/modelnet40_normal_resampled
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.val._base_.N_POINTS : 1024
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.val._base_.NUM_CATEGORY : 2
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.val._base_.USE_NORMALS : False
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.val.others = edict()
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.val.others.subset : test
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.val.others.npoints : 1024
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.val.others.bs : 1
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.test = edict()
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.test._base_ = edict()
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.test._base_.NAME : ModelNet
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.test._base_.DATA_PATH : data/ModelNet/modelnet40_normal_resampled/modelnet40_normal_resampled
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.test._base_.N_POINTS : 1024
2022-05-07 18:53:55,251 - dvae - INFO - config.dataset.test._base_.NUM_CATEGORY : 2
2022-05-07 18:53:55,252 - dvae - INFO - config.dataset.test._base_.USE_NORMALS : False
2022-05-07 18:53:55,252 - dvae - INFO - config.dataset.test.others = edict()
2022-05-07 18:53:55,252 - dvae - INFO - config.dataset.test.others.subset : test
2022-05-07 18:53:55,252 - dvae - INFO - config.dataset.test.others.npoints : 1024
2022-05-07 18:53:55,252 - dvae - INFO - config.dataset.test.others.bs : 1
2022-05-07 18:53:55,252 - dvae - INFO - config.model = edict()
2022-05-07 18:53:55,252 - dvae - INFO - config.model.NAME : DiscreteVAE
2022-05-07 18:53:55,252 - dvae - INFO - config.model.group_size : 32
2022-05-07 18:53:55,252 - dvae - INFO - config.model.num_group : 64
2022-05-07 18:53:55,252 - dvae - INFO - config.model.encoder_dims : 256
2022-05-07 18:53:55,252 - dvae - INFO - config.model.num_tokens : 8192
2022-05-07 18:53:55,252 - dvae - INFO - config.model.tokens_dims : 256
2022-05-07 18:53:55,252 - dvae - INFO - config.model.decoder_dims : 256
2022-05-07 18:53:55,252 - dvae - INFO - config.total_bs : 2
2022-05-07 18:53:55,252 - dvae - INFO - config.step_per_update : 1
2022-05-07 18:53:55,252 - dvae - INFO - config.max_epoch : 300
2022-05-07 18:53:55,252 - dvae - INFO - config.consider_metric : CDL1
2022-05-07 18:53:55,252 - dvae - INFO - Distributed training: False
2022-05-07 18:53:55,252 - dvae - INFO - Set random seed to 0, deterministic: False
2022-05-07 18:53:55,253 - ModelNet - INFO - The size of train data is 187
2022-05-07 18:53:55,253 - ModelNet - INFO - Load processed data from data/ModelNet/modelnet40_normal_resampled/modelnet40_normal_resampled/modelnet2_train_1024pts_fps.dat...
2022-05-07 18:53:55,256 - ModelNet - INFO - The size of test data is 21
2022-05-07 18:53:55,256 - ModelNet - INFO - Load processed data from data/ModelNet/modelnet40_normal_resampled/modelnet40_normal_resampled/modelnet2_test_1024pts_fps.dat...
2022-05-07 18:53:57,049 - dvae - INFO - Using Data parallel ...
2022-05-07 18:53:58,312 - dvae - INFO - [Epoch 0/300][Batch 1/93] BatchTime = 1.260 (s) DataTime = 0.051 (s) Losses = ['656.8937', '214.9319'] lr = 0.000001
2022-05-07 18:53:59,702 - dvae - INFO - [Epoch 0/300][Batch 21/93] BatchTime = 0.069 (s) DataTime = 0.002 (s) Losses = ['604.8466', '216.9617'] lr = 0.000001
2022-05-07 18:54:01,093 - dvae - INFO - [Epoch 0/300][Batch 41/93] BatchTime = 0.070 (s) DataTime = 0.001 (s) Losses = ['578.2596', '215.6334'] lr = 0.000001
2022-05-07 18:54:02,482 - dvae - INFO - [Epoch 0/300][Batch 61/93] BatchTime = 0.069 (s) DataTime = 0.002 (s) Losses = ['596.0265', '214.1100'] lr = 0.000001
2022-05-07 18:54:03,868 - dvae - INFO - [Epoch 0/300][Batch 81/93] BatchTime = 0.069 (s) DataTime = 0.002 (s) Losses = ['548.0435', '219.2712'] lr = 0.000001
2022-05-07 18:54:04,724 - dvae - INFO - [Training] EPOCH: 0 EpochTime = 7.672 (s) Losses = ['580.5861', '216.5118']
2022-05-07 18:54:07,406 - dvae - INFO - Save checkpoint at ./experiments/dvae/ModelNet_models/modelnetDvae/ckpt-last.pth
2022-05-07 18:54:07,562 - dvae - INFO - [Epoch 1/300][Batch 1/93] BatchTime = 0.154 (s) DataTime = 0.079 (s) Losses = ['549.7282', '215.7364'] lr = 0.000001
2022-05-07 18:54:08,985 - dvae - INFO - [Epoch 1/300][Batch 21/93] BatchTime = 0.071 (s) DataTime = 0.001 (s) Losses = ['511.4938', '217.7582'] lr = 0.000001
2022-05-07 18:54:10,391 - dvae - INFO - [Epoch 1/300][Batch 41/93] BatchTime = 0.069 (s) DataTime = 0.002 (s) Losses = ['518.8726', '219.2345'] lr = 0.000001
2022-05-07 18:54:11,785 - dvae - INFO - [Epoch 1/300][Batch 61/93] BatchTime = 0.069 (s) DataTime = 0.001 (s) Losses = ['482.4848', '217.2698'] lr = 0.000001
2022-05-07 18:54:13,179 - dvae - INFO - [Epoch 1/300][Batch 81/93] BatchTime = 0.070 (s) DataTime = 0.001 (s) Losses = ['478.4417', '216.4505'] lr = 0.000001
2022-05-07 18:54:14,038 - dvae - INFO - [Training] EPOCH: 1 EpochTime = 6.631 (s) Losses = ['504.2244', '216.6016']
2022-05-07 18:54:14,038 - dvae - INFO - [VALIDATION] Start validating epoch 1
2022-05-07 18:54:15,204 - dvae - INFO - [Validation] EPOCH: 1  Metrics = ['0.0011', '202.4537', '132.7796']
2022-05-07 18:54:15,204 - dvae - INFO - ============================ TEST RESULTS ============================
2022-05-07 18:54:15,204 - dvae - INFO - Taxonomy	#Sample	F-Score	CDL1	CDL2	#ModelName	
Traceback (most recent call last):
  File "main.py", line 72, in <module>
    main()
  File "main.py", line 68, in main
    run_net(args, config, train_writer, val_writer)
  File "/home/ws666/Point-BERT-master/tools/runner.py", line 191, in run_net
    metrics = validate(base_model, test_dataloader, epoch, ChamferDisL1, ChamferDisL2, val_writer, args, config, logger=logger)
  File "/home/ws666/Point-BERT-master/tools/runner.py", line 295, in validate
    msg += shapenet_dict[taxonomy_id] + '\t'
KeyError: 'ModelNet'`

**Comment by yuxumin** [comment]
Hi, 
This is because that we pass a wrong key to `shapenet_dict ('./data/shapenet_synset_dict.json')`. 

If you want to see the reconstruction metric for each class in ModelNet40, you need first:
- Modify https://github.com/lulutang0608/Point-BERT/blob/master/datasets/ModelNetDataset.py#L149 as the same as https://github.com/lulutang0608/Point-BERT/blob/master/datasets/ShapeNet55Dataset.py#L67. Return the right taxonomy id of each model, you can define a self-design `taxonomy id` according to the label of each sample.
- Create a `taxonomy : name` dict. As ./data/shapenet_synset_dict.json

Or if you do not care about the detailed metric.
Comment out https://github.com/lulutang0608/Point-BERT/blob/master/tools/runner.py#L271-L295

**Comment by sw778** [comment]
Thanks for your reply, I modified as you mentioned and it worked.

**Comment by JohanYe** [comment]
@yuxumin Is there provided code of how to mask a new dataset? I am attempting to pre-train your method on a new dataset, but it is unclear to me how i mask my data as the provided shapenet data is already masked. 
@sw778 Did u mask modelnet data yourself?
