### ISSUE TITLE
Pretrain the Point-BERT model on ModelNet

### ISSUE THREAD

**Issue by sw778** [lulutang0608/Point-BERT#39]
Hello,
I want to pretrain Point-BERT model on ModelNet40 , I trained ModelNet's dVAE model and configured .pkl weights in Point-BERT.yaml. When I run I get the following error, is this a problem with the weights file or with the distributed training? I am training with a single GPU on a machine with pytorch1.7.1, python3.7, cuda10.2.89 and cudnn7.6.5_0.

`(pointbert) ws666@ws666-OMEN-by-HP-Laptop-15-dc1xxx:~/Point-BERT-master$ bash ./scripts/dist_train_BERT.sh 1 0 --config cfgs/Mixup_models/Point-BERT.yaml --exp_name pointBERT_pretrain
+ NGPUS=1
+ PORT=0
+ PY_ARGS='--config cfgs/Mixup_models/Point-BERT.yaml --exp_name pointBERT_pretrain'
+ python -m torch.distributed.launch --master_port=0 --nproc_per_node=1 main_BERT.py --launcher pytorch --sync_bn --config cfgs/Mixup_models/Point-BERT.yaml --exp_name pointBERT_pretrain
init distributed in rank 0
2022-05-08 13:49:09,932 - Point-BERT - INFO - Copy the Config file from cfgs/Mixup_models/Point-BERT.yaml to ./experiments/Point-BERT/Mixup_models/pointBERT_pretrain/config.yaml
2022-05-08 13:49:09,933 - Point-BERT - INFO - args.config : cfgs/Mixup_models/Point-BERT.yaml
2022-05-08 13:49:09,933 - Point-BERT - INFO - args.launcher : pytorch
2022-05-08 13:49:09,933 - Point-BERT - INFO - args.local_rank : 0
2022-05-08 13:49:09,933 - Point-BERT - INFO - args.num_workers : 4
2022-05-08 13:49:09,933 - Point-BERT - INFO - args.seed : 0
2022-05-08 13:49:09,933 - Point-BERT - INFO - args.deterministic : False
2022-05-08 13:49:09,933 - Point-BERT - INFO - args.sync_bn : True
2022-05-08 13:49:09,933 - Point-BERT - INFO - args.exp_name : pointBERT_pretrain
2022-05-08 13:49:09,933 - Point-BERT - INFO - args.start_ckpts : None
2022-05-08 13:49:09,933 - Point-BERT - INFO - args.ckpts : None
2022-05-08 13:49:09,933 - Point-BERT - INFO - args.val_freq : 1
2022-05-08 13:49:09,934 - Point-BERT - INFO - args.resume : False
2022-05-08 13:49:09,934 - Point-BERT - INFO - args.test : False
2022-05-08 13:49:09,934 - Point-BERT - INFO - args.finetune_model : False
2022-05-08 13:49:09,934 - Point-BERT - INFO - args.scratch_model : False
2022-05-08 13:49:09,934 - Point-BERT - INFO - args.label_smoothing : False
2022-05-08 13:49:09,934 - Point-BERT - INFO - args.mode : None
2022-05-08 13:49:09,934 - Point-BERT - INFO - args.way : -1
2022-05-08 13:49:09,934 - Point-BERT - INFO - args.shot : -1
2022-05-08 13:49:09,934 - Point-BERT - INFO - args.fold : -1
2022-05-08 13:49:09,934 - Point-BERT - INFO - args.experiment_path : ./experiments/Point-BERT/Mixup_models/pointBERT_pretrain
2022-05-08 13:49:09,934 - Point-BERT - INFO - args.tfboard_path : ./experiments/Point-BERT/Mixup_models/TFBoard/pointBERT_pretrain
2022-05-08 13:49:09,934 - Point-BERT - INFO - args.log_name : Point-BERT
2022-05-08 13:49:09,934 - Point-BERT - INFO - args.use_gpu : True
2022-05-08 13:49:09,934 - Point-BERT - INFO - args.distributed : True
2022-05-08 13:49:09,934 - Point-BERT - INFO - args.world_size : 1
2022-05-08 13:49:09,934 - Point-BERT - INFO - config.optimizer = edict()
2022-05-08 13:49:09,934 - Point-BERT - INFO - config.optimizer.type : AdamW
2022-05-08 13:49:09,934 - Point-BERT - INFO - config.optimizer.kwargs = edict()
2022-05-08 13:49:09,934 - Point-BERT - INFO - config.optimizer.kwargs.lr : 0.0005
2022-05-08 13:49:09,934 - Point-BERT - INFO - config.optimizer.kwargs.weight_decay : 0.05
2022-05-08 13:49:09,934 - Point-BERT - INFO - config.scheduler = edict()
2022-05-08 13:49:09,934 - Point-BERT - INFO - config.scheduler.type : CosLR
2022-05-08 13:49:09,934 - Point-BERT - INFO - config.scheduler.kwargs = edict()
2022-05-08 13:49:09,934 - Point-BERT - INFO - config.scheduler.kwargs.epochs : 300
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.scheduler.kwargs.initial_epochs : 3
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset = edict()
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.train = edict()
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.train._base_ = edict()
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.train._base_.NAME : ModelNet
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.train._base_.DATA_PATH : data/ModelNet/modelnet40_normal_resampled/modelnet40_normal_resampled
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.train._base_.N_POINTS : 1024
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.train._base_.NUM_CATEGORY : 2
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.train._base_.USE_NORMALS : False
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.train.others = edict()
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.train.others.subset : train
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.train.others.npoints : 1024
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.train.others.whole : True
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.train.others.bs : 128
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.val = edict()
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.val._base_ = edict()
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.val._base_.NAME : ModelNet
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.val._base_.DATA_PATH : data/ModelNet/modelnet40_normal_resampled/modelnet40_normal_resampled
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.val._base_.N_POINTS : 1024
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.val._base_.NUM_CATEGORY : 2
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.val._base_.USE_NORMALS : False
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.val.others = edict()
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.val.others.subset : test
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.val.others.bs : 256
2022-05-08 13:49:09,935 - Point-BERT - INFO - config.dataset.extra_train = edict()
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.dataset.extra_train._base_ = edict()
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.dataset.extra_train._base_.NAME : ModelNet
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.dataset.extra_train._base_.DATA_PATH : data/ModelNet/modelnet40_normal_resampled/modelnet40_normal_resampled
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.dataset.extra_train._base_.N_POINTS : 1024
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.dataset.extra_train._base_.NUM_CATEGORY : 2
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.dataset.extra_train._base_.USE_NORMALS : False
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.dataset.extra_train.others = edict()
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.dataset.extra_train.others.subset : train
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.dataset.extra_train.others.bs : 256
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.model = edict()
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.model.NAME : Point_BERT
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.model.m : 0.999
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.model.T : 0.07
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.model.K : 16384
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.model.transformer_config = edict()
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.model.transformer_config.mask_ratio : [0.25, 0.45]
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.model.transformer_config.trans_dim : 384
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.model.transformer_config.depth : 12
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.model.transformer_config.drop_path_rate : 0.1
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.model.transformer_config.cls_dim : 512
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.model.transformer_config.replace_pob : 0.0
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.model.transformer_config.num_heads : 6
2022-05-08 13:49:09,936 - Point-BERT - INFO - config.model.transformer_config.moco_loss : False
2022-05-08 13:49:09,937 - Point-BERT - INFO - config.model.transformer_config.dvae_loss : True
2022-05-08 13:49:09,937 - Point-BERT - INFO - config.model.transformer_config.cutmix_loss : True
2022-05-08 13:49:09,937 - Point-BERT - INFO - config.model.transformer_config.return_all_tokens : False
2022-05-08 13:49:09,937 - Point-BERT - INFO - config.model.dvae_config = edict()
2022-05-08 13:49:09,937 - Point-BERT - INFO - config.model.dvae_config.group_size : 32
2022-05-08 13:49:09,937 - Point-BERT - INFO - config.model.dvae_config.num_group : 64
2022-05-08 13:49:09,937 - Point-BERT - INFO - config.model.dvae_config.encoder_dims : 256
2022-05-08 13:49:09,937 - Point-BERT - INFO - config.model.dvae_config.num_tokens : 8192
2022-05-08 13:49:09,937 - Point-BERT - INFO - config.model.dvae_config.tokens_dims : 256
2022-05-08 13:49:09,937 - Point-BERT - INFO - config.model.dvae_config.decoder_dims : 256
2022-05-08 13:49:09,937 - Point-BERT - INFO - config.model.dvae_config.ckpt : /home/ws666/Point-BERT-master/data/pretrainmodel/mydata/ckpt-best/archive/data.pkl
2022-05-08 13:49:09,937 - Point-BERT - INFO - config.total_bs : 128
2022-05-08 13:49:09,937 - Point-BERT - INFO - config.step_per_update : 1
2022-05-08 13:49:09,937 - Point-BERT - INFO - config.max_epoch : 300
2022-05-08 13:49:09,937 - Point-BERT - INFO - config.consider_metric : CDL1
2022-05-08 13:49:09,937 - Point-BERT - INFO - Distributed training: True
2022-05-08 13:49:09,937 - Point-BERT - INFO - Set random seed to 0, deterministic: False
2022-05-08 13:49:09,938 - ModelNet - INFO - The size of train data is 187
2022-05-08 13:49:09,938 - ModelNet - INFO - Load processed data from data/ModelNet/modelnet40_normal_resampled/modelnet40_normal_resampled/modelnet2_train_1024pts_fps.dat...
2022-05-08 13:49:09,941 - ModelNet - INFO - The size of test data is 21
2022-05-08 13:49:09,941 - ModelNet - INFO - Load processed data from data/ModelNet/modelnet40_normal_resampled/modelnet40_normal_resampled/modelnet2_test_1024pts_fps.dat...
2022-05-08 13:49:09,942 - ModelNet - INFO - The size of train data is 187
2022-05-08 13:49:09,942 - ModelNet - INFO - Load processed data from data/ModelNet/modelnet40_normal_resampled/modelnet40_normal_resampled/modelnet2_train_1024pts_fps.dat...
2022-05-08 13:49:09,944 - Point_BERT - INFO - [Point_BERT] build dVAE_BERT ...
2022-05-08 13:49:09,944 - Point_BERT - INFO - [Point_BERT] Point_BERT [NOT] calc the loss for all token ...
2022-05-08 13:49:09,944 - dVAE BERT - INFO - [Transformer args] {'mask_ratio': [0.25, 0.45], 'trans_dim': 384, 'depth': 12, 'drop_path_rate': 0.1, 'cls_dim': 512, 'replace_pob': 0.0, 'num_heads': 6, 'moco_loss': False, 'dvae_loss': True, 'cutmix_loss': True, 'return_all_tokens': False}
Traceback (most recent call last):
  File "/home/ws666/Point-BERT-master/utils/registry.py", line 285, in build_from_cfg
    return obj_cls(cfg)
  File "/home/ws666/Point-BERT-master/models/Point_BERT.py", line 438, in __init__
    self.transformer_q._prepare_encoder(self.config.dvae_config.ckpt)
  File "/home/ws666/Point-BERT-master/models/Point_BERT.py", line 302, in _prepare_encoder
    ckpt = torch.load(dvae_ckpt, map_location='cpu')
  File "/home/ws666/anaconda3/envs/pointbert/lib/python3.7/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ws666/anaconda3/envs/pointbert/lib/python3.7/site-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_BERT.py", line 90, in <module>
    main()
  File "main_BERT.py", line 86, in main
    pretrain(args, config, train_writer, val_writer)
  File "/home/ws666/Point-BERT-master/tools/runner_BERT_pretrain.py", line 57, in run_net
    base_model = builder.model_builder(config.model)
  File "/home/ws666/Point-BERT-master/tools/builder.py", line 34, in model_builder
    model = build_model_from_cfg(config)
  File "/home/ws666/Point-BERT-master/models/build.py", line 15, in build_model_from_cfg
    return MODELS.build(cfg, **kwargs)
  File "/home/ws666/Point-BERT-master/utils/registry.py", line 147, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/ws666/Point-BERT-master/utils/registry.py", line 288, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
_pickle.UnpicklingError: Point_BERT: A load persistent id instruction was encountered,
but no persistent_load function was specified.
Traceback (most recent call last):
  File "/home/ws666/anaconda3/envs/pointbert/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ws666/anaconda3/envs/pointbert/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ws666/anaconda3/envs/pointbert/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/ws666/anaconda3/envs/pointbert/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ws666/anaconda3/envs/pointbert/bin/python', '-u', 'main_BERT.py', '--local_rank=0', '--launcher', 'pytorch', '--sync_bn', '--config', 'cfgs/Mixup_models/Point-BERT.yaml', '--exp_name', 'pointBERT_pretrain']' returned non-zero exit status 1.
`

**Comment by yuxumin** [comment]
It seems the problem comes from torch. https://github.com/koomri/text-segmentation/issues/1#issuecomment-840419438
But why not save the model weight in `.pth`?

**Comment by sw778** [comment]
Thank you for the reminder, I modified the model weights to `.pth` and the problem was solved.
