### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by zhangdongwei1998** [lulutang0608/Point-BERT#45]
+ GPUS='0\'
+ PY_ARGS='--config cfgs/ModelNet_models/PointTransformer.yaml\ --finetune_model\ --ckpts checkpoints\ --exp_name modelnet40_1024_train'
+ CUDA_VISIBLE_DEVICES='0\'
+ python main_BERT.py --config 'cfgs/ModelNet_models/PointTransformer.yaml\' '--finetune_model\' --ckpts 'checkpoints\' --exp_name modelnet40_1024_train
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\SegTHOR\lib\site-packages\torch\utils\cpp_extension.py", line 1723, in _run_ninja_build
    env=env)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main_BERT.py", line 1, in <module>
    from tools import BERT_pretrain_run_net as pretrain
  File "E:\E21201078\Point-BERT-master\tools\__init__.py", line 1, in <module>
    from .runner import run_net
  File "E:\E21201078\Point-BERT-master\tools\runner.py", line 5, in <module>
    from tools import builder
  File "E:\E21201078\Point-BERT-master\tools\builder.py", line 8, in <module>
    from models import build_model_from_cfg
  File "E:\E21201078\Point-BERT-master\models\__init__.py", line 2, in <module>
    import models.dvae
  File "E:\E21201078\Point-BERT-master\models\dvae.py", line 4, in <module>
    from knn_cuda import KNN
  File "C:\Users\Administrator\Desktop\SegTHOR\lib\site-packages\knn_cuda\__init__.py", line 38, in <module>
    _knn = load_cpp_ext("knn")
  File "C:\Users\Administrator\Desktop\SegTHOR\lib\site-packages\knn_cuda\__init__.py", line 33, in load_cpp_ext
    with_cuda=True
  File "C:\Users\Administrator\Desktop\SegTHOR\lib\site-packages\torch\utils\cpp_extension.py", line 1136, in load
    keep_intermediates=keep_intermediates)
  File "C:\Users\Administrator\Desktop\SegTHOR\lib\site-packages\torch\utils\cpp_extension.py", line 1347, in _jit_compile
    is_standalone=is_standalone)
  File "C:\Users\Administrator\Desktop\SegTHOR\lib\site-packages\torch\utils\cpp_extension.py", line 1452, in _write_ninja_file_and_build_library
    error_prefix=f"Error building extension '{name}'")
  File "C:\Users\Administrator\Desktop\SegTHOR\lib\site-packages\torch\utils\cpp_extension.py", line 1733, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'knn': [1/1] "D:\VisualStudio\Buildtools\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64/link.exe" knn.o knn.cuda.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu
.lib torch_cuda_cu.lib -INCLUDE:?searchsorted_cuda@native@at@@YA?AVTensor@2@AEBV32@0_N1@Z torch_cuda_cpp.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:C:\Users\Administrator\Deskto
p\SegTHOR\lib\site-packages\torch\lib torch_python.lib /LIBPATH:C:\Users\Administrator\Desktop\SegTHOR\Scripts\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\lib/x64"
cudart.lib /out:knn.pyd
FAILED: knn.pyd
"D:\VisualStudio\Buildtools\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64/link.exe" knn.o knn.cuda.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda_cu.lib -INCLUDE:?searchsorted_cuda@n
ative@at@@YA?AVTensor@2@AEBV32@0_N1@Z torch_cuda_cpp.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:C:\Users\Administrator\Desktop\SegTHOR\lib\site-packages\torch\lib torch_python.l
ib /LIBPATH:C:\Users\Administrator\Desktop\SegTHOR\Scripts\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\lib/x64" cudart.lib /out:knn.pyd
LINK : fatal error LNK1104: 无法打开文件“python37.lib”
ninja: build stopped: subcommand failed.

**Comment by zhangdongwei1998** [comment]
> Hi, did you run the code on Windows? I am not familiar with torch on Windows. From the log, i think the problem come from the `knn_cuda` package. For the original knn_cuda, it doesn't support Windows (see [yuxumin/PoinTr#21 (comment)](https://github.com/yuxumin/PoinTr/issues/21#issuecomment-992328347)). I believe you can solve the problem follow the solution in [yuxumin/PoinTr#21](https://github.com/yuxumin/PoinTr/issues/21)

It worked, Thank you very much.
