### ISSUE TITLE
pretrain dvae chamfer problem

### ISSUE THREAD

**Issue by zhangdongwei1998** [lulutang0608/Point-BERT#50]
Thanks a lot for your help!
2022-06-21 13:48:35,473 - dvae - INFO - config.dataset.test = edict()
2022-06-21 13:48:35,473 - dvae - INFO - config.dataset.test._base_ = edict()
2022-06-21 13:48:35,473 - dvae - INFO - config.dataset.test._base_.NAME : ShapeNet
2022-06-21 13:48:35,473 - dvae - INFO - config.dataset.test._base_.DATA_PATH : data/ShapeNet55-34/ShapeNet-55
2022-06-21 13:48:35,473 - dvae - INFO - config.dataset.test._base_.N_POINTS : 8192
2022-06-21 13:48:35,473 - dvae - INFO - config.dataset.test._base_.PC_PATH : data/ShapeNet55-34/shapenet_pc
2022-06-21 13:48:35,473 - dvae - INFO - config.dataset.test.others = edict()
2022-06-21 13:48:35,473 - dvae - INFO - config.dataset.test.others.subset : test
2022-06-21 13:48:35,474 - dvae - INFO - config.dataset.test.others.npoints : 1024
2022-06-21 13:48:35,474 - dvae - INFO - config.dataset.test.others.bs : 1
2022-06-21 13:48:35,474 - dvae - INFO - config.model = edict()
2022-06-21 13:48:35,474 - dvae - INFO - config.model.NAME : DiscreteVAE
2022-06-21 13:48:35,474 - dvae - INFO - config.model.group_size : 32
2022-06-21 13:48:35,474 - dvae - INFO - config.model.num_group : 64
2022-06-21 13:48:35,474 - dvae - INFO - config.model.encoder_dims : 256
2022-06-21 13:48:35,474 - dvae - INFO - config.model.num_tokens : 8192
2022-06-21 13:48:35,474 - dvae - INFO - config.model.tokens_dims : 256
2022-06-21 13:48:35,474 - dvae - INFO - config.model.decoder_dims : 256
2022-06-21 13:48:35,474 - dvae - INFO - config.total_bs : 64
2022-06-21 13:48:35,475 - dvae - INFO - config.step_per_update : 1
2022-06-21 13:48:35,475 - dvae - INFO - config.max_epoch : 300
2022-06-21 13:48:35,475 - dvae - INFO - config.consider_metric : CDL1
2022-06-21 13:48:35,475 - dvae - INFO - Distributed training: False
2022-06-21 13:48:35,475 - dvae - INFO - Set random seed to 0, deterministic: False
2022-06-21 13:48:35,476 - ShapeNet-55 - INFO - [DATASET] sample out 1024 points
2022-06-21 13:48:35,476 - ShapeNet-55 - INFO - [DATASET] Open file data/ShapeNet55-34/ShapeNet-55/train.txt
2022-06-21 13:48:35,514 - ShapeNet-55 - INFO - [DATASET] 41952 instances were loaded
2022-06-21 13:48:35,515 - ShapeNet-55 - INFO - [DATASET] sample out 1024 points
2022-06-21 13:48:35,515 - ShapeNet-55 - INFO - [DATASET] Open file data/ShapeNet55-34/ShapeNet-55/test.txt
2022-06-21 13:48:35,522 - ShapeNet-55 - INFO - [DATASET] 10518 instances were loaded
2022-06-21 13:48:38,979 - dvae - INFO - Using Data parallel ...
Traceback (most recent call last):
  File "main.py", line 72, in <module>
    main()
  File "main.py", line 68, in main
    run_net(args, config, train_writer, val_writer)
  File "/home/ubuntu/E21201078/Point-BERT-master/tools/runner.py", line 132, in run_net
    loss_1, loss_2 = base_model.module.get_loss(ret, points)
  File "/home/ubuntu/E21201078/Point-BERT-master/models/dvae.py", line 320, in get_loss
    loss_recon = self.recon_loss(ret, gt)
  File "/home/ubuntu/E21201078/Point-BERT-master/models/dvae.py", line 310, in recon_loss
    loss_coarse_block = self.loss_func_cdl1(coarse, group_gt)
  File "/home/ubuntu/E21201078/common/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/E21201078/Point-BERT-master/extensions/chamfer_dist/__init__.py", line 79, in forward
    dist1, dist2 = ChamferFunction.apply(xyz1, xyz2)
  File "/home/ubuntu/E21201078/Point-BERT-master/extensions/chamfer_dist/__init__.py", line 16, in forward
    dist1, dist2, idx1, idx2 = chamfer.forward(xyz1, xyz2)
AttributeError: module 'chamfer' has no attribute 'forward'
(common) (base) ubuntu@ahu:~/E21201078/Point-BERT-master$ 

Thanks a lot for your help!

**Comment by yuxumin** [comment]
Hi, can you check if  ‘chamfer_cuda.cpp’ and 'chamfer.cu' exist under `extensions/chamfer_dist`?
